//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contensive.Addons.DistanceLearning.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contensive.Addons.DistanceLearning.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;quizlanding&quot; id=&quot;js-quizlanding&quot;&gt;
        ///	&lt;div&gt;
        ///		&lt;div&gt;
        ///			&lt;h2 id=&quot;js-quizTitle&quot;&gt;MY Sample Quiz&lt;/h2&gt;
        ///		&lt;/div&gt;
        ///		&lt;div id=&quot;js-quizStudyCopy&quot;&gt;
        ///			&lt;p&gt;&lt;b&gt;This is the start page text&lt;/b&gt;&lt;/p&gt;
        ///		&lt;/div&gt;
        ///		&lt;div id=&quot;js-quizStCustomText&quot;&gt;
        ///			&lt;p&gt;Lorem ipsum dolor sit amet, vix dicta blandit ut. Id odio modus iudico ius, ea has timeam repudiare. Sea an imperdiet cotidieque, in libris diceret eam. 
        ///			Verear perpetua ad his, ferri inermis minimum cum no. Te singulis dissentiunt neglegentur qui, an quodsi de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultLandingPageLayout {
            get {
                return ResourceManager.GetString("DefaultLandingPageLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		&lt;form method=&quot;post&quot; name=&quot;quizForm&quot; action=&quot;{{formAction}}&quot;&gt;
        ///			&lt;div class=&quot;ProgressbarCon&quot;&gt;
        ///				&lt;div class=&quot;progressbarTitle&quot;&gt;Your Progress: {{progressText}}%&lt;/div&gt;
        ///				&lt;div id=&quot;progressbar&quot;&gt;&lt;/div&gt;
        ///				&lt;br&gt;
        ///			&lt;/div&gt;
        ///			{{#questions}}
        ///				&lt;div&gt;
        ///					{{#isQuestionLink}}
        ///						&lt;div class=&quot;questionText&quot;&gt;{{{questionText}}}&lt;/div&gt;
        ///					{{/isQuestionLink}}
        ///					{{^isQuestionLink}}
        ///						{{{questionText}}}
        ///						{{#answers}}
        ///							{{#isAnswerLink}}
        ///								&lt;div class=&quot;questionChoice&quot;&gt;&lt;input typ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultQuizLayout {
            get {
                return ResourceManager.GetString("DefaultQuizLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;designBlockContainer blockQuiz {{outerContainerClass}}&quot; style=&quot;{{styleHeight}}{{styleBackgroundImage}}&quot;&gt;
        ///	&lt;div class=&quot;{{contentContainerClass}}&quot;&gt;
        ///		&lt;div class=&quot;row&quot;&gt;
        ///			&lt;div class=&quot;col-lg-12&quot;&gt;{{{legacyQuizHtml}}}&lt;/div&gt;
        ///		&lt;/div&gt;
        ///	&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string DesignBlockLayout {
            get {
                return ResourceManager.GetString("DesignBlockLayout", resourceCulture);
            }
        }
    }
}
